=== thibmeu/jafar/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "IP Prefix List",
    "type": "object",
    "properties": {
        "formatVersion": {
            "type": "string",
            "pattern": "^\\d+\\.\\d+$"
        },
        "synctoken": {
            "type": "string"
        },
        "creationTime": {
            "type": "string",
            "format": "date-time"
        },
        "notes": {
            "type": "string"
        },
        "prefixes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "ipv4Prefix": {
                        "type": "string",
                        "format": "ipv4-cidr",
                        "pattern": "^(\\b25[0-5]|\\b2[0-4][0-9]|\\b[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\\/(?:3[0-2]|[12]?\\d)$"
                    },
                    "ipv6Prefix": {
                        "type": "string",
                        "format": "ipv6-cidr",
                        "pattern": "^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]).){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\\/(?:12[0-8]|1[01]\\d|[1-9]?\\d)$"
                    },
                    "service": {
                        "type": "string"
                    }
                },
                "oneOf": [
                    {
                        "required": [
                            "ipv4Prefix"
                        ]
                    },
                    {
                        "required": [
                            "ipv6Prefix"
                        ]
                    }
                ]
            }
        }
    },
    "required": [
        "formatVersion",
        "synctoken",
        "creationTime",
        "prefixes"
    ]
}

=== thibmeu/jafar/examples/2-publication-with-multiple-services.json
{
  "$schema": "https://raw.githubusercontent.com/thibmeu/jafar/refs/heads/draft-illyes-aipref-jafar-00/schema.json",
  "formatVersion": "1.0",
  "synctoken": "example 2",
  "creationTime": "2025-09-01T10:00:00Z",
  "notes": "IP ranges for ExampleCloud services. For verification, FCrDNS is also recommended.",
  "prefixes": [
    {
      "ipv4Prefix": "192.0.2.0/24",
      "service": "TEST-NET-1"
    },
    {
      "ipv4Prefix": "198.51.100.0/24",
      "service": "TEST-NET-2"
    },
    {
      "ipv4Prefix": "203.0.113.0/24",
      "service": "TEST-NET-3"
    },
    {
      "ipv6Prefix": "2001:db8::/32",
      "service": "RFC 3849"
    },
    {
      "ipv6Prefix": "3fff::/20",
      "service": "RFC 9637"
    }
  ]
}

=== thibmeu/jafar/examples/1-basic-publication.json
{
  "$schema": "https://raw.githubusercontent.com/thibmeu/jafar/refs/heads/draft-illyes-aipref-jafar-00/schema.json",
  "formatVersion": "1.0",
  "synctoken": "example 1",
  "creationTime": "2025-08-15T14:30:00Z",
  "prefixes": [
    {
      "ipv4Prefix": "66.249.64.0/20"
    },
    {
      "ipv4Prefix": "34.64.0.0/12"
    },
    {
      "ipv6Prefix": "2001:4860:4000::/36"
    }
  ]
}
